pipeline {
  agent any
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Checkout') {
            steps {
                // Checkout the code from the repository
                git branch: 'main', url: 'https://github.com/vallepalli/Jenkins-Zero-To-Hero.git'
              script {
                    sh 'git checkout main-branch -- multi-stage-multi-agent
/HelloWorld.java'
                }
            }
        }
    stage('Build') {
            steps {
                // Compile the Java code
                sh 'javac HelloWorld.java'
            }
        }
    stage('Run') {
            steps {
                // Run the Java application
                sh 'java HelloWorld'
            }
        }
  }
}
